# az containerapp create -n my-store -g myRg --yaml deploy/container-apps/deploy.yaml
type: Microsoft.Web/containerApps
template:
  containers:
  - name: mystore
    image: ghcr.io/jeffhollan/container-app-aspnet:v0.2
    env:
    - name: APPLICATIONINSIGHTS_CONNECTION_STRING
      value: ''
kubeEnvironmentId: /subscriptions/xxxx-xxxx-xxxx/resourceGroups/myRg/providers/Microsoft.Web/kubeEnvironments/env-name
configuration:
  activeRevisionsMode: multiple
  ingress:
    external: true
    targetPort: 80