apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-store
  template:
    metadata:
      labels:
        app: my-store
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: my-store
        image: ghcr.io/jeffhollan/container-app-aspnet:v0.1
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-store
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: my-store
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-store-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - my-store-ingress.hollan.dev
    secretName: tls-secret
  rules:
  - host: my-store-ingress.hollan.dev
    http:
      paths:
      - path: /(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: my-store
            port:
              number: 80
---